apiVersion: v1 # v1
kind: Service
metadata:
  name: uniflow
  labels:
    app: uniflow
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32143 
    protocol: TCP
  selector:
    app: uniflow
  type: NodePort
